name: healthcare2050
description: A Health Care Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+16

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  http: ^0.13.0

  bottom_navy_bar: ^6.0.0
  draggable_fab: ^0.1.4
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.18
  provider:

  readmore: any
  #agora
  agora_rtc_engine: ^5.3.0
  agora_uikit: ^1.0.3
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.7

  #location
  location: ^4.4.0
  geocoding: ^2.0.5

  intl_phone_field: ^3.0.1
  connectivity_plus: any
  flutter_staggered_grid_view: ^0.6.2

  flutter_svg: any
  custom_info_window: ^1.0.1
  slide_to_act: ^2.0.1
  carousel_slider: ^4.0.0
  razorpay_flutter: ^1.3.2
  avatar_glow: ^2.0.2

 #packages for ui
  nb_utils: ^4.6.21
  sizer: ^2.0.15

  #image
  image_picker: ^0.8.5
  cached_network_image: ^3.2.0
  #calender
  calendar_timeline: ^1.0.5
  cupertino_radio_choice: ^1.0.2
  #view pdf
  flutter_cached_pdfview: ^0.4.1
  #firebase
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  firebase_analytics: ^10.0.4
  #notifications
  flutter_local_notifications: ^12.0.3
  #chating
#  flutter_chat_ui: ^1.6.4
  #logger
  logger: ^1.1.0
  # auto_otp
  sms_autofill: ^2.2.0
  #counter
  timer_count_down: ^2.2.1
  #shimmer
  shimmer: ^2.0.0
  #wakeup screen
  wakelock: any

  #100ms
  hmssdk_flutter: any
  path_provider:
  dropdown_button2: ^2.0.0
  focus_detector:
#  flutter_staggered_grid_view:
  tuple:
#  avatar_glow:
#  flutter_svg:
#  google_fonts:
#  fluttertoast:
  #  qr_code_scanner:
#  shared_preferences: 2.0.15
  #  uni_links:
  file_picker:
  draggable_widget:
  badges:
#  url_launcher:
  pip_flutter: any
  #  share_plus:
  flutter_linkify:
  flutter_foreground_task: ^3.10.0
  image_gallery_saver:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo/logo_png.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/Logo/
    - assets/gif/
    - assets/json/
    - assets/icons/


  fonts:
    - family: DancingScript
      fonts:
        - asset: googlefonts/DancingScript-VariableFont_wght.ttf

    - family: AkayaKanadaka
      fonts:
        - asset: googlefonts/AkayaKanadaka-Regular.ttf

    - family: Righteous
      fonts:
        - asset: googlefonts/Righteous-Regular.ttf

    - family: WorkSans
      fonts:
        - asset: googlefonts/WorkSans-SemiBold.ttf

    - family: Ubuntu
      fonts:
        - asset: googlefonts/Ubuntu-Regular.ttf
