// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACr6eNCxJtAgA1dz8QydEEF8X4j6XsllM',
    appId: '1:821912257151:web:a764b14e0def5eabefb54a',
    messagingSenderId: '821912257151',
    projectId: 'healthcare-1632d',
    authDomain: 'healthcare-1632d.firebaseapp.com',
    storageBucket: 'healthcare-1632d.appspot.com',
    measurementId: 'G-RVW8927PNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBszrawqfv2hYt_Zu1ZowoUJZVQdwwYqo',
    appId: '1:821912257151:android:fd59592e1fdf0faaefb54a',
    messagingSenderId: '821912257151',
    projectId: 'healthcare-1632d',
    storageBucket: 'healthcare-1632d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxsbkolWTAkQQAKjF3EggHNS1YO1vpUlI',
    appId: '1:821912257151:ios:6058eafca20d8992efb54a',
    messagingSenderId: '821912257151',
    projectId: 'healthcare-1632d',
    storageBucket: 'healthcare-1632d.appspot.com',
    iosClientId: '821912257151-a9ie1kbotm3mn51r3i72e7hg3ehnk7c6.apps.googleusercontent.com',
    iosBundleId: 'com.iigTechnology.healthcare2050',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxsbkolWTAkQQAKjF3EggHNS1YO1vpUlI',
    appId: '1:821912257151:ios:b812c68d65ff158defb54a',
    messagingSenderId: '821912257151',
    projectId: 'healthcare-1632d',
    storageBucket: 'healthcare-1632d.appspot.com',
    iosClientId: '821912257151-u2h840ib29hemj2ph9k5otd2lc6epsnk.apps.googleusercontent.com',
    iosBundleId: 'com.iigTechnologo.healthcare2050',
  );
}
